export * from './absent-articles.service';
import { AbsentArticlesService } from './absent-articles.service';
export * from './admin.service';
import { AdminService } from './admin.service';
export * from './helper.service';
import { HelperService } from './helper.service';
export * from './history.service';
import { HistoryService } from './history.service';
export * from './image.service';
import { ImageService } from './image.service';
export * from './order.service';
import { OrderService } from './order.service';
export * from './orders.service';
import { OrdersService } from './orders.service';
export * from './orders-controller.service';
import { OrdersControllerService } from './orders-controller.service';
export * from './print.service';
import { PrintService } from './print.service';
export * from './printers.service';
import { PrintersService } from './printers.service';
export * from './supplies-transition.service';
import { SuppliesTransitionService } from './supplies-transition.service';
export * from './supply.service';
import { SupplyService } from './supply.service';
export * from './supply-task.service';
import { SupplyTaskService } from './supply-task.service';
export * from './supply-tasks.service';
import { SupplyTasksService } from './supply-tasks.service';
export * from './supply-transition.service';
import { SupplyTransitionService } from './supply-transition.service';
export * from './supply-upload-record.service';
import { SupplyUploadRecordService } from './supply-upload-record.service';
export * from './task.service';
import { TaskService } from './task.service';
export * from './tenant.service';
import { TenantService } from './tenant.service';
export * from './tenants.service';
import { TenantsService } from './tenants.service';
export * from './to-stock-transition.service';
import { ToStockTransitionService } from './to-stock-transition.service';
export declare const APIS: (typeof AbsentArticlesService | typeof AdminService | typeof HelperService | typeof HistoryService | typeof ImageService | typeof OrderService | typeof OrdersService | typeof OrdersControllerService | typeof PrintService | typeof PrintersService | typeof SuppliesTransitionService | typeof SupplyService | typeof SupplyTaskService | typeof SupplyTasksService | typeof SupplyTransitionService | typeof SupplyUploadRecordService | typeof TaskService | typeof TenantService | typeof TenantsService | typeof ToStockTransitionService)[];
