export * from './absent-articles.service';
import { AbsentArticlesService } from './absent-articles.service';
export * from './absent-shelf.service';
import { AbsentShelfService } from './absent-shelf.service';
export * from './admin.service';
import { AdminService } from './admin.service';
export * from './article.service';
import { ArticleService } from './article.service';
export * from './articles.service';
import { ArticlesService } from './articles.service';
export * from './hello-world.service';
import { HelloWorldService } from './hello-world.service';
export * from './helper.service';
import { HelperService } from './helper.service';
export * from './history.service';
import { HistoryService } from './history.service';
export * from './image.service';
import { ImageService } from './image.service';
export * from './login.service';
import { LoginService } from './login.service';
export * from './managers.service';
import { ManagersService } from './managers.service';
export * from './order.service';
import { OrderService } from './order.service';
export * from './order-absend-spare-part-controller.service';
import { OrderAbsendSparePartControllerService } from './order-absend-spare-part-controller.service';
export * from './orders.service';
import { OrdersService } from './orders.service';
export * from './orders-controller.service';
import { OrdersControllerService } from './orders-controller.service';
export * from './person.service';
import { PersonService } from './person.service';
export * from './print.service';
import { PrintService } from './print.service';
export * from './print-agent.service';
import { PrintAgentService } from './print-agent.service';
export * from './printers.service';
import { PrintersService } from './printers.service';
export * from './shelf.service';
import { ShelfService } from './shelf.service';
export * from './supplies.service';
import { SuppliesService } from './supplies.service';
export * from './supplies-transition.service';
import { SuppliesTransitionService } from './supplies-transition.service';
export * from './supply.service';
import { SupplyService } from './supply.service';
export * from './supply-task.service';
import { SupplyTaskService } from './supply-task.service';
export * from './supply-tasks.service';
import { SupplyTasksService } from './supply-tasks.service';
export * from './supply-transition.service';
import { SupplyTransitionService } from './supply-transition.service';
export * from './supply-upload-record.service';
import { SupplyUploadRecordService } from './supply-upload-record.service';
export * from './system.service';
import { SystemService } from './system.service';
export * from './task.service';
import { TaskService } from './task.service';
export * from './tenant.service';
import { TenantService } from './tenant.service';
export * from './tenants.service';
import { TenantsService } from './tenants.service';
export * from './to-stock-transition.service';
import { ToStockTransitionService } from './to-stock-transition.service';
export * from './transition.service';
import { TransitionService } from './transition.service';
export * from './warehouse.service';
import { WarehouseService } from './warehouse.service';
export * from './warehouse-upload.service';
import { WarehouseUploadService } from './warehouse-upload.service';
export declare const APIS: (typeof AbsentArticlesService | typeof AbsentShelfService | typeof AdminService | typeof ArticleService | typeof ArticlesService | typeof HelloWorldService | typeof HelperService | typeof HistoryService | typeof ImageService | typeof LoginService | typeof ManagersService | typeof OrderService | typeof OrderAbsendSparePartControllerService | typeof OrdersService | typeof OrdersControllerService | typeof PersonService | typeof PrintService | typeof PrintAgentService | typeof PrintersService | typeof ShelfService | typeof SuppliesService | typeof SuppliesTransitionService | typeof SupplyService | typeof SupplyTaskService | typeof SupplyTasksService | typeof SupplyTransitionService | typeof SupplyUploadRecordService | typeof SystemService | typeof TaskService | typeof TenantService | typeof TenantsService | typeof ToStockTransitionService | typeof TransitionService | typeof WarehouseService | typeof WarehouseUploadService)[];
