/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Tenant } from './tenant';
export interface Article {
    id?: string;
    tenant?: Tenant;
    code?: string;
    name?: string;
    vendor?: string;
    article?: Article;
}
