/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PrintSringPayload } from './print-sring-payload';
import { PrintNameBarCountPayload } from './print-name-bar-count-payload';
/**
 * @type GetBarImageRequest
 * @export
 */
export type GetBarImageRequest = PrintNameBarCountPayload | PrintSringPayload;
