/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
export interface InventoryDto {
    warehouseCode: string;
    code: string;
    name: string;
    state: InventoryDto.StateEnum;
}
export declare namespace InventoryDto {
    const StateEnum: {
        readonly Uploading: "UPLOADING";
        readonly Closed: "CLOSED";
    };
    type StateEnum = typeof StateEnum[keyof typeof StateEnum];
}
