/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Tenant } from './tenant';
import { Person } from './person';
export interface Manager {
    id?: string;
    tenant?: Tenant;
    person?: Person;
}
