/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Order } from './order';
import { Article } from './article';
export interface OrderTransformRecord {
    id?: string;
    order?: Order;
    article?: Article;
    quantity?: number;
}
