/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
export interface OrderBoxDto {
    id?: string;
    code: string;
    name?: string;
    boxIndex?: number;
    state?: OrderBoxDto.StateEnum;
    openedAt?: string;
    closedAt?: string;
    personOpenLogin?: string;
    personCloseLogin?: string;
}
export declare namespace OrderBoxDto {
    const StateEnum: {
        readonly Open: "OPEN";
        readonly Closed: "CLOSED";
    };
    type StateEnum = typeof StateEnum[keyof typeof StateEnum];
}
