/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
export interface OrderUntransitionedRecordDto {
    warehouseCode?: string;
    orderCode?: string;
    vendor?: string;
    rest?: number;
    articleCode?: string;
    articleName?: string;
    sparePartCode?: string;
    sparePartName?: string;
    shelfCode?: string;
    shelfName?: string;
}
