/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Warehouse } from './warehouse';
import { OrderRecord } from './order-record';
import { OrderTransformRecord } from './order-transform-record';
export interface Order {
    id?: string;
    warehouse?: Warehouse;
    code?: string;
    name?: string;
    state?: Order.StateEnum;
    fillType?: Order.FillTypeEnum;
    orderRecords?: Set<OrderRecord>;
    orderTransformedRecords?: Set<OrderTransformRecord>;
    allowEditRecords?: boolean;
    warehouseCode?: string;
}
export declare namespace Order {
    const StateEnum: {
        readonly Uploading: "UPLOADING";
        readonly CheckedSucceded: "CHECKED_SUCCEDED";
        readonly CheckedFailed: "CHECKED_FAILED";
        readonly Transformed: "TRANSFORMED";
        readonly CalculatedSucceded: "CALCULATED_SUCCEDED";
        readonly CalculatedFailed: "CALCULATED_FAILED";
        readonly ToTransitioningSucceded: "TO_TRANSITIONING_SUCCEDED";
        readonly ToTransitioningFailed: "TO_TRANSITIONING_FAILED";
        readonly Transitioning: "TRANSITIONING";
        readonly Transitioned: "TRANSITIONED";
        readonly Closed: "CLOSED";
    };
    type StateEnum = typeof StateEnum[keyof typeof StateEnum];
    const FillTypeEnum: {
        readonly Manual: "MANUAL";
        readonly File: "FILE";
    };
    type FillTypeEnum = typeof FillTypeEnum[keyof typeof FillTypeEnum];
}
