/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Order } from './order';
import { Article } from './article';
import { Shelf } from './shelf';
export interface OrderRecord {
    id?: string;
    order?: Order;
    article?: Article;
    shelf?: Shelf;
    quantity?: number;
    rest?: number;
}
