/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Tenant } from './tenant';
import { Manager } from './manager';
export interface Person {
    id?: string;
    login?: string;
    fullName?: string;
    password?: string;
    csvImportDelimiter?: string;
    csvExportDelimiter?: string;
    printerCode?: string;
    gridPageSize?: number;
    tenant?: Tenant;
    manager?: Manager;
    admin?: boolean;
    role?: Person.RoleEnum;
}
export declare namespace Person {
    const RoleEnum: {
        readonly Admin: "ADMIN";
        readonly Manager: "MANAGER";
        readonly Employee: "EMPLOYEE";
    };
    type RoleEnum = typeof RoleEnum[keyof typeof RoleEnum];
}
