/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PrintPayload } from './print-payload';
export interface PrintNameBarCountPayload extends PrintPayload {
    value?: string;
    count?: number;
}
