/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PersonDto } from './person-dto';
import { GetBarImageRequest } from './get-bar-image-request';
export interface PrintTaskDto {
    id?: string;
    person?: PersonDto;
    payload?: GetBarImageRequest;
    timestamp?: string;
}
