/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PrintSringPayload } from './print-sring-payload';
import { PersonDto } from './person-dto';
export interface PrintTaskDto {
    id?: string;
    person?: PersonDto;
    payload?: PrintSringPayload;
    timestamp?: string;
}
