/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InventoryProcessDto } from './inventory-process-dto';
import { Metadata } from './metadata';
export interface ResponseListInventoryProcessDto {
    metadata?: Metadata;
    payload?: Array<InventoryProcessDto>;
}
