/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { YandexOAuthCallbackDto } from './yandex-o-auth-callback-dto';
import { Metadata } from './metadata';
export interface ResponseYandexOAuthCallbackDto {
    metadata?: Metadata;
    payload?: YandexOAuthCallbackDto;
}
