/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ShelfTreeNodeDto } from './shelf-tree-node-dto';
import { Metadata } from './metadata';
export interface ResponseShelfTreeNodeDto {
    metadata?: Metadata;
    payload?: ShelfTreeNodeDto;
}
