/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Metadata } from './metadata';
import { WarehouseUploadRecordDto } from './warehouse-upload-record-dto';
export interface ResponseListWarehouseUploadRecordDto {
    metadata?: Metadata;
    payload?: Array<WarehouseUploadRecordDto>;
}
