/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrderBoxDto } from './order-box-dto';
import { Metadata } from './metadata';
export interface ResponseListOrderBoxDto {
    metadata?: Metadata;
    payload?: Array<OrderBoxDto>;
}
