/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Metadata } from './metadata';
import { TurnoverRecordDto } from './turnover-record-dto';
export interface ResponseListTurnoverRecordDto {
    metadata?: Metadata;
    payload?: Array<TurnoverRecordDto>;
}
