/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Metadata } from './metadata';
import { InventoryShelvedRecordDto } from './inventory-shelved-record-dto';
export interface ResponseListInventoryShelvedRecordDto {
    metadata?: Metadata;
    payload?: Array<InventoryShelvedRecordDto>;
}
