/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Metadata } from './metadata';
import { TransitionHistoryFlatDto } from './transition-history-flat-dto';
export interface ResponseListTransitionHistoryFlatDto {
    metadata?: Metadata;
    payload?: Array<TransitionHistoryFlatDto>;
}
