/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Warehouse } from './warehouse';
export interface Shelf {
    id?: string;
    warehouse?: Warehouse;
    code?: string;
    name?: string;
    codeName?: string;
    warehouseCode?: string;
    shelf?: Shelf;
}
