/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
export interface StockDto {
    warehouseCode?: string;
    shelfCode?: string;
    articleCode?: string;
    articleName?: string;
    sparePartCode?: string;
    sparePartName?: string;
    vendor?: string;
    quantity?: number;
}
