/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Task } from './task';
import { Warehouse } from './warehouse';
import { SupplyRecord } from './supply-record';
export interface Supply {
    id?: string;
    warehouse?: Warehouse;
    code?: string;
    name?: string;
    state?: Supply.StateEnum;
    fillType?: Supply.FillTypeEnum;
    supplyRecords?: Set<SupplyRecord>;
    tasks?: Set<Task>;
    warehouseCode?: string;
}
export declare namespace Supply {
    const StateEnum: {
        readonly Uploading: "UPLOADING";
        readonly CheckedSucceded: "CHECKED_SUCCEDED";
        readonly CheckedFailed: "CHECKED_FAILED";
        readonly Transition: "TRANSITION";
        readonly Transitioned: "TRANSITIONED";
        readonly Closed: "CLOSED";
    };
    type StateEnum = typeof StateEnum[keyof typeof StateEnum];
    const FillTypeEnum: {
        readonly Manual: "MANUAL";
        readonly File: "FILE";
    };
    type FillTypeEnum = typeof FillTypeEnum[keyof typeof FillTypeEnum];
}
