/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Article } from './article';
import { Supply } from './supply';
export interface SupplyRecord {
    id?: string;
    supply?: Supply;
    article?: Article;
    price?: number;
    quantity?: number;
    rest?: number;
}
