/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Order } from './order';
import { Supply } from './supply';
import { Person } from './person';
export interface Task {
    id?: string;
    supply?: Supply;
    order?: Order;
    person?: Person;
    deleted?: boolean;
    notDeleted?: boolean;
}
