/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Manager } from './manager';
export interface Tenant {
    id?: string;
    name?: string;
    code?: string;
    language?: string;
    manager?: Manager;
}
