/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccountHistoryDto } from './account-history-dto';
export interface TransitionHistoryDto {
    id?: string;
    rollback_transaction_id?: string;
    login?: string;
    warehouseCode?: string;
    articleCode?: string;
    articleName?: string;
    debet?: AccountHistoryDto;
    credit?: AccountHistoryDto;
    quantity?: number;
    price?: number;
    timestamp?: string;
    transitionType?: TransitionHistoryDto.TransitionTypeEnum;
}
export declare namespace TransitionHistoryDto {
    const TransitionTypeEnum: {
        readonly Undefined: "UNDEFINED";
        readonly Full: "FULL";
        readonly Partial: "PARTIAL";
    };
    type TransitionTypeEnum = typeof TransitionTypeEnum[keyof typeof TransitionTypeEnum];
}
