/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
export interface TransitionFilterFlatDto {
    warehouseCode?: string;
    login?: string;
    allSupplyCode?: string;
    allOrderCode?: string;
    allShelfCode?: string;
    allOrderBoxCode?: string;
    debetSupplyCode?: string;
    debetOrderCode?: string;
    debetShelfCode?: string;
    debetOrderBoxCode?: string;
    creditSupplyCode?: string;
    creditOrderCode?: string;
    creditShelfCode?: string;
    creditOrderBoxCode?: string;
    articleCode?: string;
    quantity?: number;
    price?: number;
    fromTime?: string;
    toTime?: string;
    transitionType?: TransitionFilterFlatDto.TransitionTypeEnum;
}
export declare namespace TransitionFilterFlatDto {
    const TransitionTypeEnum: {
        readonly ToWarehouseFromOutside: "TO_WAREHOUSE_FROM_OUTSIDE";
        readonly ToOutsideFromWarehouse: "TO_OUTSIDE_FROM_WAREHOUSE";
        readonly ToWarehouseFromSupply: "TO_WAREHOUSE_FROM_SUPPLY";
        readonly ToSupplyFromWarehouse: "TO_SUPPLY_FROM_WAREHOUSE";
        readonly ToOrderFromWarehouse: "TO_ORDER_FROM_WAREHOUSE";
        readonly ToOutsideFromOrder: "TO_OUTSIDE_FROM_ORDER";
        readonly ToOrderFromOutside: "TO_ORDER_FROM_OUTSIDE";
        readonly ToWarehouseFromOrder: "TO_WAREHOUSE_FROM_ORDER";
        readonly ToWarehouseFromWarehouse: "TO_WAREHOUSE_FROM_WAREHOUSE";
        readonly ToOrderboxFromOrder: "TO_ORDERBOX_FROM_ORDER";
        readonly ToOrderFromOrderbox: "TO_ORDER_FROM_ORDERBOX";
    };
    type TransitionTypeEnum = typeof TransitionTypeEnum[keyof typeof TransitionTypeEnum];
}
