/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
export interface TransitionHistoryFlatDto {
    id?: string;
    person?: string;
    warehouseCode?: string;
    articleCode?: string;
    quantity?: number;
    price?: number;
    timestamp?: string;
    debetSupplyId?: string;
    debetSupplyCode?: string;
    debetSupplyName?: string;
    debetOrderId?: string;
    debetOrderCode?: string;
    debetOrderName?: string;
    debetShelfId?: string;
    debetShelfCode?: string;
    debetShelfName?: string;
    creditSupplyId?: string;
    creditSupplyCode?: string;
    creditSupplyName?: string;
    creditOrderId?: string;
    creditOrderCode?: string;
    creditOrderName?: string;
    creditShelfId?: string;
    creditShelfCode?: string;
    creditShelfName?: string;
    transitionType?: TransitionHistoryFlatDto.TransitionTypeEnum;
}
export declare namespace TransitionHistoryFlatDto {
    const TransitionTypeEnum: {
        readonly ToWarehouseOutOutside: "TO_WAREHOUSE_OUT_OUTSIDE";
        readonly ToOutsideFromWarehouse: "TO_OUTSIDE_FROM_WAREHOUSE";
        readonly ToWarehouseOutSupply: "TO_WAREHOUSE_OUT_SUPPLY";
        readonly ToSupplyFromwarehouse: "TO_SUPPLY_FROMWAREHOUSE";
        readonly ToOrderFromWarehouse: "TO_ORDER_FROM_WAREHOUSE";
        readonly ToOutsideFromOrder: "TO_OUTSIDE_FROM_ORDER";
        readonly ToOrderFromOutside: "TO_ORDER_FROM_OUTSIDE";
        readonly ToWarehouseFromOrder: "TO_WAREHOUSE_FROM_ORDER";
        readonly ToWarehouseFromWarehouse: "TO_WAREHOUSE_FROM_WAREHOUSE";
    };
    type TransitionTypeEnum = typeof TransitionTypeEnum[keyof typeof TransitionTypeEnum];
}
