/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
export interface TransitionFilterFlatDto {
    warehouseCode?: string;
    login?: string;
    allSupplyCode?: string;
    allOrderCode?: string;
    allShelfCode?: string;
    debetSupplyCode?: string;
    debetOrderCode?: string;
    debetShelfCode?: string;
    creditSupplyCode?: string;
    creditOrderCode?: string;
    creditShelfCode?: string;
    articleCode?: string;
    quantity?: number;
    price?: number;
    fromTime?: string;
    toTime?: string;
    transitionType?: TransitionFilterFlatDto.TransitionTypeEnum;
}
export declare namespace TransitionFilterFlatDto {
    const TransitionTypeEnum: {
        readonly Undefined: "UNDEFINED";
        readonly Full: "FULL";
        readonly Partial: "PARTIAL";
    };
    type TransitionTypeEnum = typeof TransitionTypeEnum[keyof typeof TransitionTypeEnum];
}
