/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccountFilterDto } from './account-filter-dto';
export interface TransitionFilterDto {
    tenantCode?: string;
    login?: string;
    warehouseCode?: string;
    articleCode?: string;
    all?: AccountFilterDto;
    debet?: AccountFilterDto;
    credit?: AccountFilterDto;
    quantity?: number;
    price?: number;
    fromTime?: string;
    toTime?: string;
}
