/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccountHistoryDto } from './account-history-dto';
export interface TransitionHistoryDto {
    id?: string;
    person?: string;
    warehouseCode?: string;
    articleCode?: string;
    debet?: AccountHistoryDto;
    credit?: AccountHistoryDto;
    quantity?: number;
    price?: number;
    timestamp?: string;
    transitionType?: TransitionHistoryDto.TransitionTypeEnum;
}
export declare namespace TransitionHistoryDto {
    const TransitionTypeEnum: {
        readonly ToWarehouseFromOutside: "TO_WAREHOUSE_FROM_OUTSIDE";
        readonly ToOutsideFromWarehouse: "TO_OUTSIDE_FROM_WAREHOUSE";
        readonly ToWarehouseFromSupply: "TO_WAREHOUSE_FROM_SUPPLY";
        readonly ToSupplyFromWarehouse: "TO_SUPPLY_FROM_WAREHOUSE";
        readonly ToOrderFromWarehouse: "TO_ORDER_FROM_WAREHOUSE";
        readonly ToOutsideFromOrder: "TO_OUTSIDE_FROM_ORDER";
        readonly ToOrderFromOutside: "TO_ORDER_FROM_OUTSIDE";
        readonly ToWarehouseFromOrder: "TO_WAREHOUSE_FROM_ORDER";
        readonly ToWarehouseFromWarehouse: "TO_WAREHOUSE_FROM_WAREHOUSE";
    };
    type TransitionTypeEnum = typeof TransitionTypeEnum[keyof typeof TransitionTypeEnum];
}
