/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
export interface TransitionHistoryFlatDto {
    id?: string;
    person?: string;
    warehouseCode?: string;
    articleCode?: string;
    articleName?: string;
    quantity?: number;
    price?: number;
    timestamp?: string;
    transitionType?: string;
    debetSupplyId?: string;
    debetSupplyCode?: string;
    debetSupplyName?: string;
    debetOrderId?: string;
    debetOrderCode?: string;
    debetOrderName?: string;
    debetShelfId?: string;
    debetShelfCode?: string;
    debetShelfName?: string;
    creditSupplyId?: string;
    creditSupplyCode?: string;
    creditSupplyName?: string;
    creditOrderId?: string;
    creditOrderCode?: string;
    creditOrderName?: string;
    creditShelfId?: string;
    creditShelfCode?: string;
    creditShelfName?: string;
}
