/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
export interface TurnoverRecordDto {
    warehouseCode?: string;
    articleCode?: string;
    articleName?: string;
    vendor?: string;
    soldQuantity?: number;
    middleRest?: number;
    turnover?: number;
}
