/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Warehouse } from './warehouse';
export interface WarehouseUploadRecord {
    id?: string;
    warehouse?: Warehouse;
    vendor?: string;
    articleCode?: string;
    articleName?: string;
    shelfCode?: string;
    shelfName?: string;
    quantity?: number;
    price?: number;
}
