/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
export interface WarehouseDto {
    name: string;
    code: string;
    tenant?: string;
    state?: WarehouseDto.StateEnum;
}
export declare namespace WarehouseDto {
    const StateEnum: {
        readonly Uploading: "UPLOADING";
        readonly CheckedSucceded: "CHECKED_SUCCEDED";
        readonly CheckedFailed: "CHECKED_FAILED";
        readonly Active: "ACTIVE";
    };
    type StateEnum = typeof StateEnum[keyof typeof StateEnum];
}
