/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Tenant } from './tenant';
import { Shelf } from './shelf';
import { Supply } from './supply';
export interface Warehouse {
    id?: string;
    name?: string;
    code?: string;
    tenant?: Tenant;
    state?: Warehouse.StateEnum;
    shelves?: Set<Shelf>;
    supplies?: Set<Supply>;
}
export declare namespace Warehouse {
    const StateEnum: {
        readonly Uploading: "UPLOADING";
        readonly CheckedSucceded: "CHECKED_SUCCEDED";
        readonly CheckedFailed: "CHECKED_FAILED";
        readonly Active: "ACTIVE";
    };
    type StateEnum = typeof StateEnum[keyof typeof StateEnum];
}
